spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders   # ??????: ???? 5433 ?????? 5432
    username: user
    password: secret
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-service
      auto-offset-reset: earliest
server:
  port: 8080
